### ISSUE TITLE
Model Weights

### ISSUE THREAD

**Issue by explainable-ai** [sadjava/stamp-detection#1]
Can share the dataset?

**Comment by sadjava** [comment]
Sorry, the dataset consists of confidential documents, so I cannot share it. However, there are open alternatives, such as StaVer or SPODS.

**Comment by explainable-ai** [comment]
Do you have a working link to SPODS?

**Comment by sadjava** [comment]
Unfortunately, no. Sorry for false suggestion

**Comment by explainable-ai** [comment]
Thank you!
